name: CI

on:
  push:
    branches:
        - main
 
jobs:
    build-and-push:
        name: 'Build and Push'
        runs-on: ubuntu-latest

        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Generate SHA
            id: generate_sha
            run: |
               SHA=$(echo $GITHUB_SHA | head -c7)
               echo "sha=$SHA" >> $GITHUB_OUTPUT

            # logar no container registry

          - name: Login into container registry
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME}}
              password: ${{ secrets.DOCKERHUB_TOKEN}}
        
          - name: Build docker image
            run: docker build -t denisluiz/nlw_journey_devops:${{ steps.generate_sha.outputs.sha}} .

# logar no container registry

          - name: Login into container registry
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME}}
                password: ${{ secrets.DOCKERHUB_TOKEN}}
# enviar a imagem após

          - name: Push image
            run: |
             docker push denisluiz/nlw_journey_devops:${{ steps.generate_sha.outputs.sha}}
             docker tag denisluiz/nlw_journey_devops:${{ steps.generate_sha.outputs.sha}} denisluiz
             docker push denisluiz/nlw_journey_devops:latest